name: Snap build

on:
  schedule:
    - cron: "0 0 1 */6 *" # At midnight on the 1st day of every 6th month (once per cycle).
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

env:
  SNAP_AMD64: stress-ng_${{ github.run_id}}_amd64.snap

jobs:
  build:
    outputs:
      snap: ${{ steps.snapcraft.outputs.snap }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SNAP_AMD64 }}
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.SNAP_AMD64 }}

      - name: Install snap artifact
        run: |
          sudo snap install *.snap --dangerous --devmode

      - name: Create snap alias
        run: |
          sudo snap alias stress-ng-dev.stress-ng stress-ng

      - name: Get latest tag
        id: get_tag
        run: |
          latest_tag=V$(stress-ng --version | cut -d ' ' -f 3)
          echo "Latest release: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Checkout Stress-ng source code
        uses: actions/checkout@v4
        with:
          repository: ColinIanKing/stress-ng
          ref: ${{ steps.get_tag.outputs.tag }}

      - name: Run lite-test
        run: sudo STRESS_NG=/snap/bin/stress-ng debian/tests/lite-test

      - name: Run fast-test-all
        run: sudo STRESS_NG=/snap/bin/stress-ng debian/tests/fast-test-all

      - name: Run verify-test-all
        run: sudo stress-ng --seq 0 -t 15 --pathological --times --tz --metrics --klog-check --progress --cache-enable-all -x smi || true

      - name: Run slow-test-all
        run: sudo stress-ng --seq 0 -t 5 --pathological --times --tz --metrics --verify --progress --cache-enable-all -x smi || true

